import { dependencyResolver } from "@/services/codeGeneration/dependencyResolver";

export interface PackageGeneratorOptions {
  projectName: string;
  framework?: string;
  techStack?: string[];
  description?: string;
}

export interface GeneratedPackageMetadata {
  fileName: string;
  content: string;
  dependencies: string[];
}

export class PackageGenerator {
  generate(options: PackageGeneratorOptions): GeneratedPackageMetadata {
    const resolvedStack = (options.techStack ?? []).map((entry) => entry.toLowerCase());
    const framework = (options.framework ?? "nextjs").toLowerCase();
    const dependencies = dependencyResolver.resolve({ techStack: resolvedStack, framework });

    const packageJson = {
      name: options.projectName.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "") || "generated-project",
      version: "0.1.0",
      private: true,
      description: options.description ?? "Generated by AgentForge AI",
      scripts: this.buildScripts(framework),
      dependencies: this.buildDependencies(dependencies),
      devDependencies: this.buildDevDependencies(framework),
    };

    return {
      fileName: "package.json",
      content: JSON.stringify(packageJson, null, 2),
      dependencies,
    };
  }

  private buildScripts(framework: string): Record<string, string> {
    if (framework.includes("fastapi") || framework.includes("python")) {
      return {
        dev: "uvicorn app.main:app --reload",
        start: "uvicorn app.main:app",
        lint: "python -m compileall .",
      };
    }

    if (framework.includes("express") || framework.includes("node")) {
      return {
        dev: "node --watch src/server.js",
        start: "node src/server.js",
        lint: "eslint .",
      };
    }

    return {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "eslint .",
    };
  }

  private buildDependencies(dependencies: string[]): Record<string, string> {
    return dependencies.reduce<Record<string, string>>((accumulator, dependency) => {
      if (dependency === "next") {
        accumulator[dependency] = "16.2.10";
      } else if (dependency === "react") {
        accumulator[dependency] = "19.2.4";
      } else if (dependency === "react-dom") {
        accumulator[dependency] = "19.2.4";
      } else if (dependency === "express") {
        accumulator[dependency] = "^5.1.0";
      } else if (dependency === "dotenv") {
        accumulator[dependency] = "^16.4.5";
      } else if (dependency === "prisma") {
        accumulator[dependency] = "^6.0.0";
      } else if (dependency === "@prisma/client") {
        accumulator[dependency] = "^6.0.0";
      } else if (dependency === "fastapi") {
        accumulator[dependency] = "^0.115.0";
      } else if (dependency === "uvicorn") {
        accumulator[dependency] = "^0.30.6";
      } else if (dependency === "python-dotenv") {
        accumulator[dependency] = "^1.0.1";
      } else if (dependency === "pg") {
        accumulator[dependency] = "^8.13.0";
      } else if (dependency === "mongodb") {
        accumulator[dependency] = "^6.0.0";
      } else if (dependency === "docker") {
        accumulator[dependency] = "^24.0.0";
      }

      return accumulator;
    }, {});
  }

  private buildDevDependencies(framework: string): Record<string, string> {
    if (framework.includes("fastapi") || framework.includes("python")) {
      return {
        python: "^3.12.0",
      };
    }

    if (framework.includes("express") || framework.includes("node")) {
      return {
        eslint: "^9.11.0",
        "@types/node": "^20.17.10",
      };
    }

    return {
      "@types/node": "^20.17.10",
      "@types/react": "^19.2.0",
      "@types/react-dom": "^19.2.0",
      eslint: "^9.11.0",
      typescript: "^5.8.3",
      tailwindcss: "^4.1.12",
      autoprefixer: "^10.4.20",
      postcss: "^8.4.49",
    };
  }
}

export const packageGenerator = new PackageGenerator();
