import type { ProjectBuilderSnapshot } from "@/services/projectBuilder";
import type { Project } from "@/types/project";

export class ReadmeGenerator {
  generate(snapshot: ProjectBuilderSnapshot, project?: Project): string {
    const projectName = project?.name ?? snapshot.manifest?.projectName ?? "AgentForge Project";
    const description = project?.description ?? "A production-ready application orchestrated through AgentForge.";
    const framework = snapshot.manifest?.framework ?? snapshot.projectSummary.framework;
    const packageManager = snapshot.manifest?.packageManager ?? snapshot.projectSummary.packageManager;
    const environmentVariables = snapshot.manifest?.environmentVariables ?? [];
    const componentCount = snapshot.projectSummary.components;
    const routeCount = snapshot.projectSummary.routes;
    const fileCount = snapshot.projectSummary.filesGenerated;
    const routeList = snapshot.previewManifest.pages.map((page) => `- ${page.route}`).join("\n");

    return [
      `# ${projectName}`,
      "",
      description,
      "",
      "## Overview",
      `This project was generated by AgentForge AI and packaged for direct export. It includes ${fileCount} generated files across ${componentCount} UI components and ${routeCount} routes/workflows.`,
      "",
      "## Stack",
      `- Framework: ${framework}`,
      `- Package Manager: ${packageManager}`,
      "- Runtime: Next.js + TypeScript",
      "",
      "## Features",
      "- Modular orchestration structure",
      "- Reusable service layer",
      "- Generated project packaging with canonical docs",
      "- Direct ZIP export workflow",
      "",
      "## Installation",
      "```bash",
      "npm install",
      "npm run dev",
      "```",
      "",
      "## Environment",
      environmentVariables.length > 0
        ? environmentVariables.map((variable) => `- ${variable}`).join("\n")
        : "- Add your environment variables through the project configuration file.",
      "",
      "## Routes",
      routeList || "- No preview routes were detected in the current snapshot.",
      "",
      "## Notes",
      "Use the workspace export controls to package and download the generated output.",
      "",
      "## License",
      "This project is distributed as generated output for the current workspace session.",
    ].join("\n");
  }
}

export const readmeGenerator = new ReadmeGenerator();
